version: '3.3'

services:
  php-env:
    build: .
    volumes:
      - ./manajemen:/var/www/html
    ports:
      - 8383:80
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ccmsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./manajemen:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8384:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql